### ISSUE TITLE
Give up on Python 3.6

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [jjhelmus/nmrglue#184]
At least give up in CI tests because Python 3.6 is not available any more:

![Python 3 6](https://user-images.githubusercontent.com/3234522/206116349-2fb2f45a-5757-4961-9519-7285a292d26e.png)

**Comment by jjhelmus** [comment]
Python 3.6 has reached end-of-life and is no longer supported by the CPython developers, see https://devguide.python.org/versions/ for details.  

I'm in favor or removing support, or at least not testing against this Python version.  

It is worth noting that the wider scientific Python community recommends libraries support Python 3.8 and above at this time, see [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html). Based on this policy it was recommended to drop support for Python 3.6 in June of 2020.
