### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by guykl** [jjhelmus/nmrglue#63]
Hi,
I have many 1H NMR files from a bruker machine, and I am looking for specific compounds.
Is it possible to use nmrglue to search through files for specific peaks? For example: search for a triplet at 4.01 in 20 different 1H spectra and tell in which spectrum this exists?

Thanks,
Guy

**Comment by jjhelmus** [comment]
nmrglue does not have this type of analysis as a build in function. I script that performed such a search could be written in Python and using the reading, processing, and analysis functions in nmrglue would help but a no "turn key" solution to finding peaks at a specific location is provided by the package.
