### ISSUE TITLE
plotting example: plot_2d_spectrum, example data missing

### ISSUE THREAD

**Issue by Melisius** [jjhelmus/nmrglue#77]
Hi,

The link for the example data is broken.
http://nmrglue.googlecode.com/files/example_plot_2d.zip, gives:

404. That’s an error.

The requested URL /files/example_plot_2d.zip was not found on this server. That’s all we know.

**Comment by jjhelmus** [comment]
You should be able to find the data via https://code.google.com/archive/p/nmrglue/downloads.  Happy to accept PR to fix the broken links.
