### ISSUE TITLE
TOPSPIN 4 Incompatible to read processed files 

### ISSUE THREAD

**Issue by witheve17** [jjhelmus/nmrglue#86]
Bruker has recently updated there processed file format so when you try to use nmr glue to read a processed file it reds incorrectly the 2rr, and 1r files. I am not sure what changes in the new topspin.

**Comment by jjhelmus** [comment]
Can you provide an example of the file in the new format?

**Comment by witheve17** [comment]
I have attached the zipped experimental folder 
[189.zip](https://github.com/jjhelmus/nmrglue/files/2464977/189.zip)

**Comment by jjhelmus** [comment]
I do not have access to TOPSPIN so I do not know how this data is expected to look.  Plotting the data using the current development version of nmrglue gives a plot that is similar to the on in the `thumb.png` file:

![figure_1](https://user-images.githubusercontent.com/1050278/47057819-ef470800-d187-11e8-8818-6b84d9b9cc5e.png)

Do you have any 1D data and a plot that I could compare with?

**Comment by witheve17** [comment]
Hi Jonathan,

Thank you for replying. This is how the data is supposed to look. However when I import the data using nmrglue this is what I get for plotting.

This is the code that I use to import the data.

dic, data = ng.bruker.read_pdata('/opt/topspin35pl7/data/Velencia_ABBrushOp/155/pdata/1')
udic = ng.bruker.guess_udic(dic, data)
uc=ng.fileiobase.uc_from_udic(udic)
ppm = uc.ppm_scale()
cl = data.std() * 2 * 1.2 ** np.arange(10)
fig = plt.figure()
ax = fig.add_subplot(111)
ax.contour(data, cl, colors='blue')
plt.show()

This is the resulting graphic.


[/var/folders/yr/7qr6dznx18vgw9w70hvn_dzh001tkf/T/com.microsoft.Outlook/Content.MSO/96ACEECE.tmp]

How ever in topspin there is just one major peak.

Before this I erase nmrglue from my conda nmr processing environment and reinstalled into the environment using conda.
When I evaluate the comman conda list:

nmrglue                   0.5                      py35_0    jjhelmus
is the version that I have,

I am operating Mac Osx HighSierra  I use jupyter notebook as my python interface.

Thank you for your attention to this matter.

Best,
--
Velencia Witherspoon
NRC-NIST Postdoctoral Fellow
Functional Polymers Group
Material Science and Engineering Division
National Institute of Standards and Technology
Email: vjw@nist.gov<mailto:vjw@nist.gov>
Phone: 301-975-4736

**Comment by kaustubhmote** [comment]
This seems to be related to #81. The change in Topspin 4.0 is the swirch to storing the raw and processed data as floats rather than integers. I can reproduce the issue with nmrglue v0.5 and v0.6, but it seems to work fine with v0.7-dev. 

@witheve17, you will have to download the current development version from github and install it manually to be able to read the data in correctly.

**Comment by jjhelmus** [comment]
I agree with @kaustubhmote, upgrading to nmrglue version 0.6 should fix the issue.  If you want to install the development version you can do this using `pip install git+https://github.com/jjhelmus/nmrglue.git`.

**Comment by witheve17** [comment]
Hi Thank I have completely uninstalled and re-installed nmrglue and the issue has been fixed.

--
Velencia Witherspoon
NRC-NIST Postdoctoral Fellow
Functional Polymers Group
Material Science and Engineering Division
National Institute of Standards and Technology
Email: vjw@nist.gov<mailto:vjw@nist.gov>
Phone: 301-975-4736

**Comment by jjhelmus** [comment]
Great to hear!
